//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package co.experian.computec.sts.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "obtenerToken", namespace = "http://sts.computec.experian.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerToken", namespace = "http://sts.computec.experian.co/")
public class ObtenerToken {

	@XmlElement(name = "arg0", namespace = "")
	private co.experian.computec.sts.model.ComputecSTSDTO arg0;

	/**
	 * 
	 * @return returns ComputecSTSDTO
	 */
	public co.experian.computec.sts.model.ComputecSTSDTO getArg0() {
		return this.arg0;
	}

	/**
	 * 
	 * @param arg0
	 *            the value for the arg0 property
	 */
	public void setArg0(co.experian.computec.sts.model.ComputecSTSDTO arg0) {
		this.arg0 = arg0;
	}

}
